// Offline narration generator for a single-file @lessonkit/author lesson. Unlike the
// per-example generators (which export a `lessonSpec`), an author lesson does
// `export default lesson(...)` — a LessonBuilder — so we read its `.spec`. It synthesizes
// real ElevenLabs audio (or, with --fake, deterministic silent clips), caches raw
// responses, and writes a `.gen.ts` module the host imports: the narration-prepared spec
// (audio-driven scene durations + caption cues), the audio manifest (base64 mp3 + word
// timings), and caption segments.
//   tsx author/gen-audio.ts <lesson.ts> <out.gen.ts> [voiceId] [--fake]
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { prepareNarration, type LessonSpec } from "@lessonkit/lesson";
import { elevenLabsAdapter, fakeTtsAdapter, fileCache, type TtsAdapter } from "@lessonkit/audio";

const argv = process.argv.slice(2);
const fake = argv.includes("--fake");
const [lessonArg, outArg, voice] = argv.filter((a) => a !== "--fake");
if (!lessonArg || !outArg) {
  console.error("usage: tsx author/gen-audio.ts <lesson.ts> <out.gen.ts> [voiceId] [--fake]");
  process.exit(1);
}

let adapter: TtsAdapter;
if (fake) {
  adapter = fakeTtsAdapter();
} else {
  const key = process.env.ELEVEN_LABS_API_KEY || process.env.ELEVENLABS_API_KEY;
  if (!key) {
    console.error("Set ELEVEN_LABS_API_KEY (or ELEVENLABS_API_KEY), or pass --fake for silent test audio.");
    process.exit(1);
  }
  adapter = elevenLabsAdapter({ apiKey: key, ...(voice ? { voice } : {}) });
}

const lessonPath = resolve(process.cwd(), lessonArg);
const outPath = resolve(process.cwd(), outArg);
const mod = (await import(lessonPath)) as { default?: { spec?: LessonSpec } };
const spec = mod.default?.spec;
if (!spec) {
  console.error(`${lessonArg} must \`export default lesson(...)\` from @lessonkit/author.`);
  process.exit(1);
}

const cacheDir = resolve(dirname(outPath), ".audio-cache");
mkdirSync(dirname(outPath), { recursive: true });
mkdirSync(cacheDir, { recursive: true });

console.log(`Synthesizing narration for "${spec.title}" (${fake ? "fake/silent" : "ElevenLabs"})…`);
const prepared = await prepareNarration(spec, { adapter, cache: fileCache(cacheDir) });

const narrated = Object.keys(prepared.audio);
const secs = narrated.map((id) => (prepared.audio[id]!.durationMs / 1000).toFixed(1));
console.log(
  narrated.length
    ? `  ${narrated.length} narrated beats: ${narrated.map((id, i) => `${id}=${secs[i]}s`).join(", ")}`
    : "  (no narrated beats — nothing to synthesize)",
);

const banner = `// AUTO-GENERATED by author/gen-audio.ts (${fake ? "--fake silent" : "ElevenLabs"}). Do not edit.\n`;
const body =
  `import type { LessonSpec } from "@lessonkit/lesson";\n` +
  `import type { AudioManifest, CaptionSegment } from "@lessonkit/audio";\n\n` +
  `export const preparedSpec: LessonSpec = ${JSON.stringify(prepared.spec)};\n\n` +
  `export const audioManifest: AudioManifest = ${JSON.stringify(prepared.audio)};\n\n` +
  `export const captions: Record<string, CaptionSegment[]> = ${JSON.stringify(prepared.captions)};\n`;
writeFileSync(outPath, banner + body);
console.log(`Wrote ${outPath} (${(Buffer.byteLength(banner + body) / 1024).toFixed(0)} KB)`);
