// Offline narration generator (like SocraticAI's generate_audio.py). Synthesizes
// real ElevenLabs audio for a lesson's narrated scenes, caches raw responses, and
// writes a `.gen.ts` module the browser app imports: the narration-prepared spec
// (audio-driven durations + caption cues), the audio manifest (base64 mp3 + word
// timings), and caption segments. Run: tsx examples/gen-audio.ts <lessonModule> <out> [voice]
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { prepareNarration } from "@lessonkit/lesson";
import { elevenLabsAdapter, fileCache } from "@lessonkit/audio";

const [lessonArg, outArg, voice] = process.argv.slice(2);
if (!lessonArg || !outArg) {
  console.error("usage: tsx examples/gen-audio.ts <lessonModule.ts> <out.gen.ts> [voiceId]");
  process.exit(1);
}
const key = process.env.ELEVEN_LABS_API_KEY || process.env.ELEVENLABS_API_KEY;
if (!key) {
  console.error("Set ELEVEN_LABS_API_KEY (or ELEVENLABS_API_KEY).");
  process.exit(1);
}

const lessonPath = resolve(process.cwd(), lessonArg);
const outPath = resolve(process.cwd(), outArg);
const { lessonSpec } = (await import(lessonPath)) as { lessonSpec: import("@lessonkit/lesson").LessonSpec };

const cacheDir = resolve(dirname(outPath), ".audio-cache");
mkdirSync(cacheDir, { recursive: true });

console.log(`Synthesizing narration for "${lessonSpec.title}" (ElevenLabs)…`);
const prepared = await prepareNarration(lessonSpec, {
  adapter: elevenLabsAdapter({ apiKey: key, ...(voice ? { voice } : {}) }),
  cache: fileCache(cacheDir),
});

const narrated = Object.keys(prepared.audio);
const secs = narrated.map((id) => (prepared.audio[id]!.durationMs / 1000).toFixed(1));
console.log(`  ${narrated.length} scenes: ${narrated.map((id, i) => `${id}=${secs[i]}s`).join(", ")}`);

const banner = "// AUTO-GENERATED by examples/gen-audio.ts — real ElevenLabs audio. Do not edit.\n";
const body =
  `import type { LessonSpec } from "@lessonkit/lesson";\n` +
  `import type { AudioManifest, CaptionSegment } from "@lessonkit/audio";\n\n` +
  `export const preparedSpec: LessonSpec = ${JSON.stringify(prepared.spec)};\n\n` +
  `export const audioManifest: AudioManifest = ${JSON.stringify(prepared.audio)};\n\n` +
  `export const captions: Record<string, CaptionSegment[]> = ${JSON.stringify(prepared.captions)};\n`;
writeFileSync(outPath, banner + body);
const kb = (Buffer.byteLength(banner + body) / 1024).toFixed(0);
console.log(`Wrote ${outPath} (${kb} KB)`);
