// Offline narration for the flagship. Tries real ElevenLabs (key from env or
// ~/.bashrc — whose line has a stray space that breaks bash export, so we parse it
// ourselves) and FALLS BACK to the deterministic fake adapter so audio.gen.ts
// always exists. Writes preparedSpec (audio-driven durations + caption cues) +
// manifest + captions. Run: tsx examples/flagship/gen-audio.ts
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { resolve } from "node:path";
import { prepareNarration } from "@lessonkit/lesson";
import { elevenLabsAdapter, fakeTtsAdapter, fileCache, type TtsAdapter } from "@lessonkit/audio";
import { lessonSpec } from "./lesson.js";

function keyFromBashrc(): string | null {
  try {
    const rc = readFileSync(resolve(homedir(), ".bashrc"), "utf8");
    const m = /ELEVEN_?LABS_API_KEY\s*=\s*["']?([A-Za-z0-9_\-]{20,})/.exec(rc);
    return m ? m[1]! : null;
  } catch {
    return null;
  }
}

const key = process.env.ELEVEN_LABS_API_KEY || process.env.ELEVENLABS_API_KEY || keyFromBashrc();
const out = resolve(process.cwd(), "examples/flagship/audio.gen.ts");
const cacheDir = resolve(process.cwd(), "examples/flagship/.audio-cache");
mkdirSync(cacheDir, { recursive: true });

async function prep(adapter: TtsAdapter, label: string): Promise<Awaited<ReturnType<typeof prepareNarration>>> {
  console.log(`Synthesizing narration (${label})…`);
  return prepareNarration(lessonSpec, { adapter, cache: fileCache(cacheDir) });
}

let prepared: Awaited<ReturnType<typeof prepareNarration>>;
if (key) {
  try {
    prepared = await prep(elevenLabsAdapter({ apiKey: key }), "ElevenLabs (real voice)");
  } catch (e) {
    console.warn(`  ElevenLabs unavailable → silent fallback: ${String(e).split("\n")[0]}`);
    prepared = await prep(fakeTtsAdapter(), "fake / silent (timing only)");
  }
} else {
  console.warn("  No ElevenLabs key found → silent fallback.");
  prepared = await prep(fakeTtsAdapter(), "fake / silent (timing only)");
}

const narrated = Object.keys(prepared.audio);
console.log(`  ${narrated.length} narrated scenes: ${narrated.join(", ")}`);
const banner = "// AUTO-GENERATED by examples/flagship/gen-audio.ts. Do not edit.\n";
const body =
  `import type { LessonSpec } from "@lessonkit/lesson";\n` +
  `import type { AudioManifest, CaptionSegment } from "@lessonkit/audio";\n\n` +
  `export const preparedSpec: LessonSpec = ${JSON.stringify(prepared.spec)};\n\n` +
  `export const audioManifest: AudioManifest = ${JSON.stringify(prepared.audio)};\n\n` +
  `export const captions: Record<string, CaptionSegment[]> = ${JSON.stringify(prepared.captions)};\n`;
writeFileSync(out, banner + body);
console.log(`Wrote ${out} (${(Buffer.byteLength(banner + body) / 1024).toFixed(0)} KB)`);
